### ISSUE TITLE
Some minor design suggestions

### ISSUE THREAD

**Issue by TheAndroidGuy** [MikaelEdebro/vue-airbnb-style-datepicker#2]
Hello, thank you for making this awesome component.
Thank you for the CDN version.
I have some minor design suggestions:

1. The buttons (change-month-button and action-buttons) could have `cursor: pointer;` style.
2. The date buttons could have `:hover` color
3. The change-month-buttons could have `:focused` colors
4. The `day.in-range` buttons could have normal font-weight, not bold
5. The selected days buttons borders could have `#33dacd` color
6. The hidden months affect the height of the datepicker, and sometimes there is unnecessary empty space at the bottom.

I know 5 of these are easy to fix/change and people can change them in the CSS styles, but i wanted to give these suggestions to make it more similar to the [original component](http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

Thank you for making this component.

**Comment by TheAndroidGuy** [comment]
By the way `If a valid date is pasted to the input, datepicker should select it.` is awesome feature.

**Comment by Codermar** [comment]
Optional Time selectors would be really nice as well.

**Comment by Codermar** [comment]
It's a great start but without looking too deep into this component I see:
- Keyboard navigation needs work

**Comment by TheAndroidGuy** [comment]
@MikaelEdebro how can i set datepickerOptions for the CDN version?

**Comment by MikaelEdebro** [comment]
@TheAndroidGuy I changed the implementation for the CDN version. So it no longer automatically installs the plugin. Instead, you have to do it yourself. Fix available in 1.5.0
See updated docs.
https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/USAGE-WITH-CDN.html

**Comment by TheAndroidGuy** [comment]
@MikaelEdebro when i change the content of the days array, it shows the date at wrong day position.
Also how can i set custom month names?

**Comment by TheAndroidGuy** [comment]
@MikaelEdebro It still doesn't work. There is something wrong with the day at position [3] (Thursday) when i change its content (even add . or , or empty space) it gives wrong date position. Try it.

**Comment by MikaelEdebro** [comment]
@TheAndroidGuy Should be fixed now in version 1.6.
I also added support for passing localized month names.
https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/INSTALLATION.html#plugin-options

**Comment by TheAndroidGuy** [comment]
The feature of opening the datepicker on focus would be nice.
Also instead of text `invalid date` it can set the date to null when the date is invalid (so validation can work).
